title: Ayan Banerjee
logo: https://avatars.githubusercontent.com/u/179697030?s=400&u=997c6c41a502a97378db749bee6705743790ee3d&v=4
description: Data Analyst
show_downloads: false
#google_analytics:
theme: jekyll-theme-minimal
email: ayan292004banerjee@gmail.com
linkedin: https://www.linkedin.com/in/ayan-banerjee-b8234b321
github: https://github.com/AyanBanerjee29
portfolio_pdf: https://cdn.jsdelivr.net/gh/AyanBanerjee29/Portfolio@main/Portfolio.pdf
#profile_photo: https://avatars.githubusercontent.com/u/179697030?s=400&v=4
