title: Ayan Banerjee
logo: https://avatars.githubusercontent.com/u/179697030?s=400&u=997c6c41a502a97378db749bee6705743790ee3d&v=4
description: Data Analyst
#show_downloads: false
#google_analytics:
footer: false

theme: jekyll-theme-minimal
